version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        ports:
            - '8080:80'
        environment:
            DATABASE_URL: 'mysql://root:@127.0.0.1:3306/rule_engine'
            MAILER_DSN: 'smtp://mailhog:1025'
            SLACK_DSN: 'slack://xoxb-7677929630689-7662400538613-UaTJQn5PZoGMENpmc1wz3faw@default'
            MESSENGER_TRANSPORT_DSN: 'doctrine://default'

    database:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_DATABASE: rule_engine
        ports:
            - '3306:3306'

    mailhog:
        image: mailhog/mailhog
        ports:
            - '1025:1025'
            - '8025:8025'
